### ISSUE TITLE
Removing Hydrator recipes using CraftTweaker causes ConcurrentModificationException

### ISSUE THREAD

**Issue by sk2048** [Lothrazar/Cyclic#1100]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2815

Mod Version: 1.18.5

CraftTweaker Version: 4.1.17

Single Player or Server: Either

Describe problem (what you were doing / what happened):
Using the [example ZenScript file](https://github.com/Lothrazar/Cyclic/blob/develop/scripts_zen_example/hydrator.zs) raises the following exception which is printed in the crafttweaker log.
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: crafttweaker.zs}: null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.lothrazar.cyclicmagic.compat.crafttweaker.RecipeHydrateZen.removeShapedRecipe(RecipeHydrateZen.java:43)
	at Crafttweaker.__script__(crafttweaker.zs:6)
	at __ZenMain__.run(Crafttweaker)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:221)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:101)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:814)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:624)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

The recipe is removed, but CraftTweaker stops execution at this point. The subsequent addition of a recipe is not performed. This makes it impossible to replace a Hydrator recipe.

Log file (text block or link): https://hastebin.com/favopebuqe.md

**Comment by Lothrazar** [comment]
Releasing a fix soon, with that the error is gone with multiple items

Hydrator.removeShapedRecipe(minecraft:grass);
Hydrator.removeShapedRecipe(minecraft:grass_path);
Hydrator.removeShapedRecipe(minecraft:clay_ball);
Hydrator.removeShapedRecipe(minecraft:concrete);

**Comment by Lothrazar** [comment]
1.19.2 https://minecraft.curseforge.com/projects/cyclic/files/2698577

**Comment by sk2048** [comment]
Thank you very much for the quick fix
