### ISSUE TITLE
Error with high level excavation enchantment

### ISSUE THREAD

**Issue by Nefaro** [Lothrazar/Cyclic#1283]
**Minecraft Version:** 1.14.4
**Forge Version:** 28.1.109
**Mod Version:** 1.14.4-0.1.2
**Single Player or Server:** single

Playing a modpack (Enigmatica 4) that has modified enchantment levels (I assume Apotheosis modpack) and I have a pickaxe with "Excavation V" enchantment. Using this pickaxe causes an index out of bounds exception (posted on the bottom)

Looking at the code, there are 4 levels defined. While the issue itself is with a modpack that uses the enchantment in an unintended way, it would be nice if this mod (Cyclic) could handle this situation, either by capping the usable level internally, or better yet, by defining the increments arithmetically (and letting the modpack suffer the consequences)

Thank you for your work.

`java.lang.ArrayIndexOutOfBoundsException: 5
	at com.lothrazar.cyclic.enchant.EnchantExcavation.getHarvestMax(EnchantExcavation.java:61) ~[?:1.14.4-0.1.2] {re:classloading}
	at com.lothrazar.cyclic.enchant.EnchantExcavation.harvestSurrounding(EnchantExcavation.java:99) ~[?:1.14.4-0.1.2] {re:classloading}
	at com.lothrazar.cyclic.enchant.EnchantExcavation.onBreakEvent(EnchantExcavation.java:88) ~[?:1.14.4-0.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1069_EnchantExcavation_onBreakEvent_BreakEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:565) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:215) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:85) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:315) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:ServerPlayerEntity.handleFalling}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerWorld$$Lambda$11875/813827594.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}`

**Comment by Lothrazar** [comment]
Fixed in 1.15 https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2882784 

Keeping the other version open in case i have time for 1.14
