### ISSUE TITLE
Incompatibility bug with  Decocraft-2.6.3_1.12.2

### ISSUE THREAD

**Issue by Lazersgm** [Lothrazar/Cyclic#1293]
Minecraft Version: 
1.12
Forge Version: 
forge-1.12.2-14.23.5.2838
Mod Version: 
1.12.2-1.19.19
Single Player or Server:
server
Describe problem (what you were doing; what happened; what should have happened):
starting server

Log file link:
https://pastebin.com/ytdWp2Eu
Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Cause of bug is the mod "com/mia/craftstudio" . no mention of com.lothrazar.cyclic in the crash log


Source of error from your log:

`[01:36:31] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: com/mia/craftstudio/IPackReaderCallback
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
    at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]`
