### ISSUE TITLE
Wireless transmitter causing repeated Fatal Errors

### ISSUE THREAD

**Issue by ChaoticLogic** [Lothrazar/Cyclic#942]
Minecraft version & Mod Version: 
Minecraft 1.12.2
Cyclic 1.16.9

Single player or Server: Singleplayer

Describe problem (what you were doing / what happened): I was not receiving the expected power from solar panels added by Solar Flux Reborn when used with the wireless transmitter. The battery serves as a good intermediary when other mods have power compatibility issues (Hatchery methane generator -> Immersive Engineering LV wires). I placed a battery in between the solar panels and the wireless transmitter, but still was not getting power transfer.

The minecraft log revealed repeating errors like this:

> [16:45:21] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException

I uprooted the entire operation which stopped the error messages and began placing block again one at a time. Only when the wireless transmitter was placed did this section of code start repeating in the log again.

Crash log (if any): No crash occurred.

**Comment by PrinceOfAmber** [comment]
Are you able to get the full log file ? (it will have things like forge version, modlist, etc).  

Also how far apart was the transmitter, it sounds like very close like the same room.

**Comment by PrinceOfAmber** [comment]
I lit up a few connected to lamps and had no issues. nether and overworld.  

Nothing in the log file shows a "cyclicmagic" java file so i dont even know where to start

**Comment by ChaoticLogic** [comment]
Thank you for your patience, the last couple days have been very hectic.
I'll see about getting you that log info shortly. If your testing shows no
log errors, I may have a conflict in my modpack.

**Comment by ChaoticLogic** [comment]
[ChaoticLogic log file.txt](https://github.com/PrinceOfAmber/Cyclic/files/2453215/ChaoticLogic.log.file.txt)

Attached is the log file.  It includes game startup and loading my superflat testing world. My only action was to place the energy transfer node. If you're using Notepad++, you'll find the error messages begin at line 2734.  I've inserted a gap with a comment noting this location in case you're using another editor.

I performed a search of the error messages and you are correct, there is no mention of "cyclic" anywhere. It is, in fact, coming from waila! I will copy this over to that mod author as well.

Here's the lines:
`Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]`

**Comment by sscards55** [comment]
This happens with just Hwyla and Cyclic installed. I believe this happens because the transmitter is supposed to contain a tank but the tank is null, causing issues with Hwyla.

**Comment by Lothrazar** [comment]
Thanks for your patience.  New versions are much more stable than the old ones so this looks fine now.

Also error appears to be from the other mod anyway, as you said

Caused by: java.lang.NullPointerException at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?] at
